# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jumper < Formula
  desc "Quickly jump to your project directories"
  homepage "https://github.com/M-Porter/jumper"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/M-Porter/jumper/releases/download/v0.4.0/jumper_0.4.0_darwin_arm64.tar.gz"
      sha256 "e712e70dafbadf95e0c3ebe7167704e05c6ac25293cb788a6104fca5239aa322"

      def install
        bin.install "jumper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/M-Porter/jumper/releases/download/v0.4.0/jumper_0.4.0_darwin_amd64.tar.gz"
      sha256 "6b6695009833afbc475d3cac5df2674c02ae5d1263107402aa8a45a6c0a29bde"

      def install
        bin.install "jumper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/M-Porter/jumper/releases/download/v0.4.0/jumper_0.4.0_linux_arm64.tar.gz"
      sha256 "098b86a35b6a3b7e930d4de79c82a121a2ccb7247e300fd1a37a0f8c26f2d47f"

      def install
        bin.install "jumper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/M-Porter/jumper/releases/download/v0.4.0/jumper_0.4.0_linux_amd64.tar.gz"
      sha256 "7830f3627036f019a6a25deb6e55fbca1bbcf4af5e32588c8eea636dcd5ee044"

      def install
        bin.install "jumper"
      end
    end
  end

  def caveats; <<~EOS
    Run `jumper setup` for setup instructions.
  EOS
  end
end
