# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jumper < Formula
  desc "Quickly jump to your project directories"
  homepage "https://github.com/M-Porter/jumper"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/M-Porter/jumper/releases/download/v2.3.0/jumper_2.3.0_darwin_amd64.tar.gz"
      sha256 "fb871c19082641e425d7563f5b8e8bca601fc7a4276596366d89512e8cc506f9"

      define_method(:install) do
        bin.install "jumper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/M-Porter/jumper/releases/download/v2.3.0/jumper_2.3.0_darwin_arm64.tar.gz"
      sha256 "f5a9484320aef26687dd5b06550cc51620ad0548fab7254fcff140c724370d11"

      define_method(:install) do
        bin.install "jumper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/M-Porter/jumper/releases/download/v2.3.0/jumper_2.3.0_linux_amd64.tar.gz"
      sha256 "d8e2fa01c2b3e8fabc3b89c24460dacb4d3280f8f4ac65562848857b9b9ccebf"
      define_method(:install) do
        bin.install "jumper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/M-Porter/jumper/releases/download/v2.3.0/jumper_2.3.0_linux_arm64.tar.gz"
      sha256 "21b57f53c5fad3020bf083046aefd608b28515ce2f31ebe25b0da298c9090aef"
      define_method(:install) do
        bin.install "jumper"
      end
    end
  end

  def caveats
    <<~EOS
      Run `jumper setup` for setup instructions.
    EOS
  end
end
