# This file was generated by GoReleaser. DO NOT EDIT.
cask "jumper" do
  name "jumper"
  desc "Quickly jump to your project directories"
  homepage "https://github.com/M-Porter/jumper"
  version "2.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jumper"

  on_macos do
    on_intel do
      url "https://github.com/M-Porter/jumper/releases/download/v#{version}/jumper_#{version}_darwin_amd64.tar.gz"
      sha256 "18d75466da2f7187a338c536f152528d189132f9e2431443197e221fbb2d7066"
    end
    on_arm do
      url "https://github.com/M-Porter/jumper/releases/download/v#{version}/jumper_#{version}_darwin_arm64.tar.gz"
      sha256 "36655fe706bee0545d468f97c2de820ec365a74c96a77a2f67419f075446952e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/M-Porter/jumper/releases/download/v#{version}/jumper_#{version}_linux_amd64.tar.gz"
      sha256 "eff96c5f1665a0a250e432b58cc4da407dcd4a4270e2d928034d270f3022f71a"
    end
    on_arm do
      url "https://github.com/M-Porter/jumper/releases/download/v#{version}/jumper_#{version}_linux_arm64.tar.gz"
      sha256 "21e53681d46d7e6e9eeea3e007b8b7400c63f3579fa1739d38a7ecfd638cdbf8"
    end
  end

  caveats do
    "See the README for setup instructions: https://github.com/M-Porter/jumper#readme"
  end

  # No zap stanza required
end
