# This file was generated by GoReleaser. DO NOT EDIT.
cask "jumper" do
  name "jumper"
  desc "Quickly jump to your project directories"
  homepage "https://github.com/M-Porter/jumper"
  version "2.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jumper"

  on_macos do
    on_intel do
      url "https://github.com/M-Porter/jumper/releases/download/v#{version}/jumper_#{version}_darwin_amd64.tar.gz"
      sha256 "61ac8fb4f513df45357b2afebd80fed905ae264f115d1008b34ba1d320eb2684"
    end
    on_arm do
      url "https://github.com/M-Porter/jumper/releases/download/v#{version}/jumper_#{version}_darwin_arm64.tar.gz"
      sha256 "7f2693c66d562da8354e7d477e8a8e64979fdd44bbbf3b96d33fb5b92a399829"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/M-Porter/jumper/releases/download/v#{version}/jumper_#{version}_linux_amd64.tar.gz"
      sha256 "b286301db38de2466b65b378682ca130f06b9c0211586a66230b09cdc4736d51"
    end
    on_arm do
      url "https://github.com/M-Porter/jumper/releases/download/v#{version}/jumper_#{version}_linux_arm64.tar.gz"
      sha256 "3332c4f34e90624260d2b4b051df992c0d5ab06c5891dec6dde4d82bc2914d65"
    end
  end

  caveats do
    "See the README for setup instructions: https://github.com/M-Porter/jumper#readme"
  end

  # No zap stanza required
end
